const menu = [
  { name: "Vanilla", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Strawberry", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Pineapple", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Chickoo", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Coee Caramel", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Plain Chocolate", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Bubble Gum", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Mango", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Chickoo Chocolate", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Oreo Cookie", notes: "Cream", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Paan Masala", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Gulkand", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Buer Scotch", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Vanilla Chips", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Rose Malai", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Mango Malai", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Kaju Draksh", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Chocolate Chips", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Black Current", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Kaju Anjeer", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Kaju Badam", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Mava Malai", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Almond Caramel", category: 'American Thickshake', rate: [{ price: 90, qty: '250ml' }] },
  { name: "Kaju Gulkand", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kaju Mango", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kesar Pista", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kaju Khajur", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Choco Crunch", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Gulab Masti", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Nuy Nutella", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kit Kat", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Dairy Milk", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Walnut Chocolate", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Fresh Kiwi", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Fresh Sitafal", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Crunchy Red Velvet", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Roasted Almond", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kaju Chocolate", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Dryfruit", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Fresh Strawberry", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Pista Malai", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Rajbhog", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Lotus Bisco", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kaju Coconut", category: 'American Thickshake', rate: [{ price: 140, qty: '250ml' }] },
  { name: "Kaju Katri", category: 'American Thickshake', rate: [{ price: 150, qty: '250ml' }] },
  { name: "Choco Brownie", category: 'American Thickshake', rate: [{ price: 160, qty: '250ml' }] },
  { name: "Maakhan Bhog", category: 'American Thickshake', rate: [{ price: 160, qty: '250ml' }] },
  { name: "Rajwadi Kaju", category: 'American Thickshake', rate: [{ price: 160, qty: '250ml' }] },
  { name: "Kaju Malai Tukda", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "Kaju Anjeer Tukda", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "Kaju Badam Tukda", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "Fresh Mango", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "American Dryfruit", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "Rajwadi Dryfruit", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "Rocher Ferrero", category: 'American Thickshake', rate: [{ price: 170, qty: '250ml' }] },
  { name: "Dryfruit Khazana", category: 'American Thickshake', rate: [{ price: 180, qty: '250ml' }] },

  { name: "Mastani", category: 'Special Falooda', rate: [{ price: 70, qty: '250ml' }] },
  { name: "Shalimar", category: 'Special Falooda', rate: [{ price: 80, qty: '250ml' }] },
  { name: "Rose Falooda", category: 'Special Falooda', rate: [{ price: 120, qty: '300ml' }] },
  { name: "Mango Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Strawberry Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Green Pista Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Chocolate Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Red Rose Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Black Current Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Badam Pista Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Kaju Anjeer Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Kesar Pista Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Sitafal Falooda", category: 'Special Falooda', rate: [{ price: 160, qty: '300ml' }] },
  { name: "Rajwadi Falooda", category: 'Special Falooda', rate: [{ price: 170, qty: '300ml' }] },
  { name: "Rajbhog Falooda", category: 'Special Falooda', rate: [{ price: 170, qty: '300ml' }] },

  { name: "Mastani", category: 'Special Falooda', rate: [{ price: 70, qty: '250ml' }] },
  { name: "Shalimar", category: 'Special Falooda', rate: [{ price: 80, qty: '250ml' }] },
  { name: "Rose Falooda", category: 'Special Falooda', rate: [{ price: 120, qty: '300ml' }] },
  { name: "Mango Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Strawberry Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Green Pista Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Chocolate Falooda", category: 'Special Falooda', rate: [{ price: 140, qty: '300ml' }] },
  { name: "Red Rose Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Black Current Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Badam Pista Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Kaju Anjeer Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Kesar Pista Falooda", category: 'Special Falooda', rate: [{ price: 150, qty: '300ml' }] },
  { name: "Sitafal Falooda", category: 'Special Falooda', rate: [{ price: 160, qty: '300ml' }] },
  { name: "Rajwadi Falooda", category: 'Special Falooda', rate: [{ price: 170, qty: '300ml' }] },
  { name: "Rajbhog Falooda", category: 'Special Falooda', rate: [{ price: 170, qty: '300ml' }] },

  { name: "Nimbu Sikanji", category: 'Juice Shots', rate: [{ price: 60, qty: '2 Shots' }, { price: 70, qty: '4 Shots' }] },
  { name: "Jamun", category: 'Juice Shots', rate: [{ price: 110, qty: '2 Shots' }, { price: 190, qty: '4 Shots' }] },
  { name: "Guava Chilly", category: 'Juice Shots', rate: [{ price: 110, qty: '2 Shots' }, { price: 190, qty: '4 Shots' }] },
  { name: "Strawberry", category: 'Juice Shots', rate: [{ price: 110, qty: '2 Shots' }, { price: 190, qty: '4 Shots' }] },
  { name: "Kiwi", category: 'Juice Shots', rate: [{ price: 120, qty: '2 Shots' }, { price: 210, qty: '4 Shots' }] },
  { name: "Litchi", category: 'Juice Shots', rate: [{ price: 120, qty: '2 Shots' }, { price: 210, qty: '4 Shots' }] }
]

