export const menu = [{
  category: 'American Thickshake',
  image: './assets/falooda.png',
  color: '#751daa',
  items: [
    { name: "Vanilla", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Strawberry", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Pineapple", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Chickoo", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Coee Caramel", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Plain Chocolate", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Bubble Gum", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Mango", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Chickoo Chocolate", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Oreo Cookie", notes: "Cream", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Paan Masala", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Gulkand", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Buer Scotch", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Vanilla Chips", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Rose Malai", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Mango Malai", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Kaju Draksh", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Chocolate Chips", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Black Current", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Kaju Anjeer", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Kaju Badam", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Mava Malai", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Almond Caramel", rate: [{ price: 90, qty: '250ml' }] },
    { name: "Kaju Gulkand", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kaju Mango", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kesar Pista", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kaju Khajur", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Choco Crunch", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Gulab Masti", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Nuy Nutella", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kit Kat", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Dairy Milk", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Walnut Chocolate", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Fresh Kiwi", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Fresh Sitafal", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Crunchy Red Velvet", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Roasted Almond", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kaju Chocolate", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Dryfruit", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Fresh Strawberry", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Pista Malai", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Rajbhog", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Lotus Bisco", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kaju Coconut", rate: [{ price: 140, qty: '250ml' }] },
    { name: "Kaju Katri", rate: [{ price: 150, qty: '250ml' }] },
    { name: "Choco Brownie", rate: [{ price: 160, qty: '250ml' }] },
    { name: "Maakhan Bhog", rate: [{ price: 160, qty: '250ml' }] },
    { name: "Rajwadi Kaju", rate: [{ price: 160, qty: '250ml' }] },
    { name: "Kaju Malai Tukda", rate: [{ price: 170, qty: '250ml' }] },
    { name: "Kaju Anjeer Tukda", rate: [{ price: 170, qty: '250ml' }] },
    { name: "Kaju Badam Tukda", rate: [{ price: 170, qty: '250ml' }] },
    { name: "Fresh Mango", rate: [{ price: 170, qty: '250ml' }] },
    { name: "American Dryfruit", rate: [{ price: 170, qty: '250ml' }] },
    { name: "Rajwadi Dryfruit", rate: [{ price: 170, qty: '250ml' }] },
    { name: "Rocher Ferrero", rate: [{ price: 170, qty: '250ml' }] },
    { name: "Dryfruit Khazana", rate: [{ price: 180, qty: '250ml' }] },
  ]
}, {
  category: 'Special Falooda',
  color: '#2687ab',
  items: [
    { name: "Mastani", rate: [{ price: 70, qty: '250ml' }] },
    { name: "Shalimar", rate: [{ price: 80, qty: '250ml' }] },
    { name: "Rose Falooda", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Mango Falooda", rate: [{ price: 140, qty: '300ml' }] },
    { name: "Strawberry Falooda", rate: [{ price: 140, qty: '300ml' }] },
    { name: "Green Pista Falooda", rate: [{ price: 140, qty: '300ml' }] },
    { name: "Chocolate Falooda", rate: [{ price: 140, qty: '300ml' }] },
    { name: "Red Rose Falooda", rate: [{ price: 150, qty: '300ml' }] },
    { name: "Black Current Falooda", rate: [{ price: 150, qty: '300ml' }] },
    { name: "Badam Pista Falooda", rate: [{ price: 150, qty: '300ml' }] },
    { name: "Kaju Anjeer Falooda", rate: [{ price: 150, qty: '300ml' }] },
    { name: "Kesar Pista Falooda", rate: [{ price: 150, qty: '300ml' }] },
    { name: "Sitafal Falooda", rate: [{ price: 160, qty: '300ml' }] },
    { name: "Rajwadi Falooda", rate: [{ price: 170, qty: '300ml' }] },
    { name: "Rajbhog Falooda", rate: [{ price: 170, qty: '300ml' }] },
  ]
}, {
  category: "Fresh Juice",
  color: '#ad6d00',
  items: [
    { name: "Mosambi", rate: [{ price: 60, qty: '250ml' }] },
    { name: "Watermelon", rate: [{ price: 60, qty: '250ml' }] },
    { name: "Pineapple", rate: [{ price: 70, qty: '250ml' }] },
    { name: "Orange", rate: [{ price: 80, qty: '300ml' }] },
    { name: "Jambu", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Kiwi", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Apple", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Dadam", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Mango", notes: "Seasonal", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Strawberry", notes: "Seasonal", rate: [{ price: 120, qty: '300ml' }] },
  ]
}, {
  category: 'Smoothies Primium Milkshake',
  color: '#b5437b',
  items: [
    { name: "Vanilla", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Bubblegum", rate: [{ price: 140, qty: '300ml' }] },
    { name: "Oreo Cookies", rate: [{ price: 140, qty: '300ml' }] },
    { name: "Fresh Chickoo", rate: [{ price: 150, qty: '300ml' }] },
    { name: "Fresh Strawberry", rate: [{ price: 160, qty: '300ml' }] },
    { name: "Mango Milk", rate: [{ price: 160, qty: '300ml' }] },
    { name: "Black Current", rate: [{ price: 160, qty: '300ml' }] },
    { name: "Chocolate Chips", rate: [{ price: 160, qty: '300ml' }] },
    { name: "Fresh Guava", rate: [{ price: 170, qty: '300ml' }] },
    { name: "Fresh Sitafal", rate: [{ price: 170, qty: '300ml' }] },
    { name: "Coee Mocha", rate: [{ price: 170, qty: '300ml' }] },
    { name: "Blueberry", rate: [{ price: 170, qty: '300ml' }] },
    { name: "KitKat", rate: [{ price: 170, qty: '300ml' }] },
    { name: "Kaju Anjeer", rate: [{ price: 180, qty: '300ml' }] },
    { name: "Dairy Milk", rate: [{ price: 180, qty: '300ml' }] },
    { name: "Dark Chocolate", rate: [{ price: 180, qty: '300ml' }] },
    { name: "Choco Brownie", rate: [{ price: 180, qty: '300ml' }] },
    { name: "Nutella", rate: [{ price: 180, qty: '300ml' }] },
    { name: "Walnut Chocolate Fudge", rate: [{ price: 180, qty: '300ml' }] },
    { name: "Avocado", rate: [{ price: 220, qty: '300ml' }] },
    { name: "Rocher Ferrero", rate: [{ price: 220, qty: '300ml' }] },
    { name: "Lotus Bisco", rate: [{ price: 220, qty: '300ml' }] },
  ]
}, {
  category: 'Cold Coco',
  color: '#8f56b3',
  items: [
    { name: "Cold Coco", rate: [{ price: 70, qty: '250ml' }] },
    { name: "Icecream Coco", rate: [{ price: 100, qty: '300ml' }] },
    { name: "Cadbury Coco", rate: [{ price: 100, qty: '300ml' }] },
    { name: "Nutella Coco", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Kaju Coco", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Malai Coco", rate: [{ price: 120, qty: '300ml' }] },
    { name: "Rajwadi Coco", rate: [{ price: 170, qty: '300ml' }] },
    { name: "Coco", rate: [{ price: 200, qty: '1 litre' }] },
  ]
}, {
  category: 'Lassi',
  color: '#8f56b3',
  items: [
    { name: "Lassi", rate: [{ price: 50, qty: '250ml' }] },
    { name: "Rose Lassi", rate: [{ price: 60, qty: '300ml' }] },
    { name: "Mango Lassi", rate: [{ price: 70, qty: '300ml' }] },
    { name: "Malai Lassi", rate: [{ price: 80, qty: '300ml' }] },
    { name: "Kaju Lassi", rate: [{ price: 80, qty: '300ml' }] },
    { name: "Rajwadi Lassi ", rate: [{ price: 120, qty: '300ml' }] },
  ]
}, {
  category: 'Juice Shots',
  color: '#8f56b3',
  items: [
    { name: "Nimbu Sikanji", rate: [{ price: 60, qty: '2 Shots' }, { price: 70, qty: '4 Shots' }] },
    { name: "Jamun", rate: [{ price: 110, qty: '2 Shots' }, { price: 190, qty: '4 Shots' }] },
    { name: "Guava Chilly", rate: [{ price: 110, qty: '2 Shots' }, { price: 190, qty: '4 Shots' }] },
    { name: "Strawberry", rate: [{ price: 110, qty: '2 Shots' }, { price: 190, qty: '4 Shots' }] },
    { name: "Kiwi", rate: [{ price: 120, qty: '2 Shots' }, { price: 210, qty: '4 Shots' }] },
    { name: "Litchi", rate: [{ price: 120, qty: '2 Shots' }, { price: 210, qty: '4 Shots' }] }
  ]
}, {
  category: 'Rabdi',
  color: '#8f56b3',
  items: [
    { name: "Angoor Rabdi", rate: [{ price: 100, qty: '200ml' }] },
    { name: "Sitafal Rabdi", rate: [{ price: 120, qty: '200ml' }] },
    { name: "Kesar Dryfruit Rabdi", rate: [{ price: 130, qty: '200ml' }] },
  ]
}, {
  category: 'Live Ice-creams (Dryfruit Lovers)',
  color: '#8f56b3',
  items: [
    { name: "Kaju Anjeer", rate: [{ price: 150, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Kaju Draksh", rate: [{ price: 150, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Kaju Gulkand", rate: [{ price: 150, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "American Dryfruit", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Rajbhog", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Honey Almond", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Kaju Katli", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Kesar Pista", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Dryfruit Khazana", rate: [{ price: 180, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Roasted Almond", rate: [{ price: 180, qty: "Roll(150ml)\nFog(200ml)" }] }
  ]
}, {
  category: 'Live Ice-creams (Chocolate Lovers)',
  color: '#8f56b3',
  items: [
    { name: "Chocolate Chips", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Nutella Chocolate", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "KitKat Chunks", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Dairy Milk", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Choco Rock Brownie", rate: [{ price: 180, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Choco Walnut", rate: [{ price: 180, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Rocher Ferrero", rate: [{ price: 220, qty: "Roll(150ml)\nFog(200ml)" }] },
  ]
}, {
  category: 'Live Ice-creams (Our Signature)',
  color: '#8f56b3',
  items: [
    { name: "Oreo Cookies", rate: [{ price: 150, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Lotus Bisco", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Paan Masala", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Mava Malai", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Buer Scotch", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Tender Coconut", rate: [{ price: 170, qty: "Roll(150ml)\nFog(200ml)" }] },
  ]
}, {
  category: 'Live Ice-creams (Fruits & Berries)',
  color: '#8f56b3',
  items: [
    { name: "Fresh Strawberry", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Mango Malai", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Fresh Sitafal", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Fresh Jambu", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Fresh Litchi", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Fresh kiwi", rate: [{ price: 160, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Guava Chilly", rate: [{ price: 180, qty: "Roll(150ml)\nFog(200ml)" }] },
    { name: "Shetur (Mulberry)", rate: [{ price: 180, qty: "Roll(150ml)\nFog(200ml)" }] },
  ]
}, {
  category: 'Icecream Sundaes',
  color: '#8f56b3',
  items: [
    { name: "Fresh Gotala", rate: [{ price: 180, qty: '2 Scoop' }] },
    { name: "Jelly Malai Pineapple", rate: [{ price: 180, qty: '2 Scoop' }] },
    { name: "Mava Masti Gotala", rate: [{ price: 210, qty: '2 Scoop' }] },
    { name: "Chocolate Chips Gotala", rate: [{ price: 210, qty: '2 Scoop' }] },
    { name: "Tripple Sundae", rate: [{ price: 210, qty: '3 scoop' }] },
    { name: "Choco Dance", rate: [{ price: 210, qty: '3 scoop' }] },
    { name: "Dryfruit Gotala", rate: [{ price: 230, qty: '2 Scoop' }] },
    { name: "Lotus Bisco Sundae", rate: [{ price: 250, qty: '3 Scoop' }] },
    { name: "Hungama", rate: [{ price: 250, qty: '5 Scoop' }] },
    { name: "Subkuch", rate: [{ price: 300, qty: '6 Scoop' }] },
    { name: "Rocher Sundae", rate: [{ price: 380, qty: '3 Scoop' }] },
  ]
}, {
  category: 'Premium Icecream Handscoops & Cone',
  color: '#8f56b3',
  items: [
    { name: "Vanilla", rate: [{ price: 40, qty: '100ml' }, { price: 140, qty: '500ml' }] },
    { name: "Mango", rate: [{ price: 50, qty: '100ml' }, { price: 190, qty: '500ml' }] },
    { name: "Bubblegum", rate: [{ price: 50, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Fresh Strawberry", rate: [{ price: 60, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Kaju Draksh", rate: [{ price: 60, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Mava Malai", rate: [{ price: 60, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Buerscotch", rate: [{ price: 60, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Kaju Anjeer", rate: [{ price: 70, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Sugar Free Vanilla", rate: [{ price: 70, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Chocolate Chips", rate: [{ price: 70, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "Rose Almond", rate: [{ price: 70, qty: '100ml' }, { price: 210, qty: '500ml' }] },
    { name: "American Dryfruit", rate: [{ price: 70, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Royal Rajbhog", rate: [{ price: 70, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Black Current", rate: [{ price: 70, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Kesar Pista", rate: [{ price: 70, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Chocolate Marble", rate: [{ price: 70, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Fresh Jamun", rate: [{ price: 80, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Fresh Sitafal", rate: [{ price: 80, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Fresh Blueberry", rate: [{ price: 80, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Fresh Chickoo", rate: [{ price: 80, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Fresh Guava", rate: [{ price: 80, qty: '100ml' }, { price: 240, qty: '500ml' }] },
    { name: "Nutella", rate: [{ price: 90, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Walnut Chocolate Fudge", rate: [{ price: 90, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Belgium Dark Chocolate", rate: [{ price: 90, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Dry Fruit Khazana", rate: [{ price: 90, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Rosted Almond", rate: [{ price: 90, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Choco Rock Brownie", rate: [{ price: 100, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Lotus Bisco", rate: [{ price: 100, qty: '100ml' }, { price: 280, qty: '500ml' }] },
    { name: "Rocher Ferrero", rate: [{ price: 110, qty: '100ml' }, { price: 310, qty: '500ml' }] },
  ]
}, {
  category: 'Sp. Fresh Cream (Seasonal)',
  color: '#8f56b3',
  items: [
    { name: "Cream Fruit Salad", rate: [{ price: 80, qty: '250ml' }] },
    { name: "Sp. Cream Salad", rate: [{ price: 200, qty: '300ml' }] },
    { name: "Fresh Strawberry Cream", rate: [{ price: 200, qty: '300ml' }] },
    { name: "Fresh Mango Cream", rate: [{ price: 220, qty: '300ml' }] },
    { name: "Fresh Sitafal Cream", rate: [{ price: 220, qty: '300ml' }] },
    { name: "Dryfruit Cream", rate: [{ price: 220, qty: '300ml' }] },
    { name: "Rainbow Dryfruit Cream", rate: [{ price: 240, qty: '300ml' }] },
  ]
}, {
  category: 'Browine & Sizzler',
  color: '#8f56b3',
  items: [
    { name: "Sizzling Hot Chocolate Brownie", rate: [{ price: 180 }] },
    { name: "Hot Kit Kat Brownie", rate: [{ price: 210 }] },
    { name: "51 Rainbow Sp. Double Decker Brownie", rate: [{ price: 230 }] },
    { name: "Hot Nutella Rocher Brownie", rate: [{ price: 260 }] },
  ]
}, {
  category: 'Stick Kulfi',
  color: '#8f56b3',
  items: [
    { name: "Mava Malai", rate: [{ price: 30, qty: '60ml' }] },
    { name: "Sitafal", rate: [{ price: 30, qty: '60ml' }] },
    { name: "Chikoo", rate: [{ price: 30, qty: '60ml' }] },
    { name: "Kaju Anjeer", rate: [{ price: 30, qty: '60ml' }] },
    { name: "Black Beauty", rate: [{ price: 30, qty: '60ml' }] },
    { name: "Litchi", rate: [{ price: 30, qty: '60ml' }] },
    { name: "Rose Kaju", rate: [{ price: 30, qty: '60ml' }] },
  ]
}, {
  category: 'Family Pack',
  color: '#8f56b3',
  items: [
    { name: "Fresh Strawberry", rate: [{ price: 260, qty: '750ml' }] },
    { name: "Fresh Mango", rate: [{ price: 260, qty: '750ml' }] },
    { name: "Bubblegum", rate: [{ price: 260, qty: '750ml' }] },
    { name: "Mava Malai", rate: [{ price: 260, qty: '750ml' }] },
    { name: "Birthday Cake", rate: [{ price: 260, qty: '750ml' }] },
    { name: "Rocher Ferrero", rate: [{ price: 300, qty: '750ml' }] },
    { name: "Choco Rock Brownie", rate: [{ price: 300, qty: '750ml' }] },
    { name: "Lotus Bisco", rate: [{ price: 300, qty: '750ml' }] },
    { name: "Roasted Almond", rate: [{ price: 300, qty: '750ml' }] },
    { name: "Dry Fruit Khazana", rate: [{ price: 300, qty: '750ml' }] },
    { name: "Sitafal", rate: [{ price: 300, qty: '750ml' }] },
    { name: "Walnut Chocolate Fudge", rate: [{ price: 300, qty: '750ml' }] },
  ]
}, {
  category: 'Randeri Kulfi & Kulfi Falooda',
  color: '#8f56b3',
  items: [
    { name: "Fresh Sitafal", rate: [{ price: 100, qty: 'Kulfi (130ml)' }, { price: 180, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Kaju Mango", rate: [{ price: 100, qty: 'Kulfi (130ml)' }, { price: 180, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Kit Kat", rate: [{ price: 100, qty: 'Kulfi (130ml)' }, { price: 180, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Kaju Katri", rate: [{ price: 100, qty: 'Kulfi (130ml)' }, { price: 180, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Kesar Pista", rate: [{ price: 120, qty: 'Kulfi (130ml)' }, { price: 180, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Roasted Almond", rate: [{ price: 120, qty: 'Kulfi (130ml)' }, { price: 190, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Bisco Roll", rate: [{ price: 140, qty: 'Kulfi (130ml)' }, { price: 200, qty: 'Kulfi Falooda\n(250ml)' }] },
    { name: "Pista Roll", rate: [{ price: 150, qty: 'Kulfi (130ml)' }, { price: 220, qty: 'Kulfi Falooda\n(250ml)' }] },
  ]
}];
